import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { Navbar } from "@/components/Navbar";
import { TerminalCard } from "@/components/TerminalCard";
import { useVerifyEntry } from "@/hooks/use-linera";
import { Search, ShieldCheck, Database, AlertCircle, FileDown, CheckCircle2 } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { jsPDF } from "jspdf";
import "jspdf-autotable";

export default function Verify() {
  const [location] = useLocation();
  const [inputValue, setInputValue] = useState("");
  const [searchId, setSearchId] = useState<number | null>(null);
  const [showSuccess, setShowSuccess] = useState(false);
  
  // Extract ID from URL params on load
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const idParam = params.get("id");
    if (idParam) {
      setInputValue(idParam);
      const parts = idParam.split(":");
      const id = parts.length >= 3 ? parseInt(parts[2]) : parseInt(idParam);
      if (!isNaN(id)) setSearchId(id);
    }
  }, []);

  const { data, isLoading, isError, error } = useVerifyEntry(searchId);

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputValue) return;
    
    // Parse format: linera:<chain_id>:<entry_index>
    const parts = inputValue.split(":");
    let id: number;
    
    if (parts.length >= 3) {
      id = parseInt(parts[2]);
    } else {
      id = parseInt(inputValue);
    }
    
    if (!isNaN(id)) {
      setSearchId(id);
    }
  };

  useEffect(() => {
    if (data) {
      setShowSuccess(true);
      const timer = setTimeout(() => setShowSuccess(false), 5000);
      return () => clearTimeout(timer);
    }
  }, [data]);

  const downloadPDF = () => {
    if (!data) return;

    const doc = new jsPDF();
    const verifyId = `linera:${data.chainId}:${data.id}`;
    
    // Page Settings
    const margin = 20;
    const pageWidth = doc.internal.pageSize.width;
    const contentWidth = pageWidth - (margin * 2);

    // Header
    doc.setFontSize(24);
    doc.setTextColor(107, 70, 193); // Purple accent
    doc.text("LineraMind — Verified AI Answer", margin, 25);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, 32, pageWidth - margin, 32);

    let currentY = 45;

    // Section Helper
    const addSection = (title: string, content: string | string[], isSummary = false) => {
      // Check overflow
      if (currentY > 250) {
        doc.addPage();
        currentY = 25;
      }

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(100, 100, 100);
      doc.text(title, margin, currentY);
      currentY += 8;

      doc.setDrawColor(240, 240, 240);
      doc.line(margin, currentY, margin + 40, currentY);
      currentY += 10;

      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0, 0, 0);

      if (Array.isArray(content)) {
        content.forEach(point => {
          const lines = doc.splitTextToSize(`• ${point}`, contentWidth - 5);
          doc.text(lines, margin + 5, currentY);
          currentY += (lines.length * 6) + 2;
        });
      } else {
        const cleanContent = content.replace(/\*\*(.*?)\*\*/g, '$1')
                                   .replace(/^\s*[-*]\s+/gm, '')
                                   .replace(/###/g, '')
                                   .replace(/```[\s\S]*?```/g, '');
        const lines = doc.splitTextToSize(cleanContent, contentWidth);
        doc.text(lines, margin, currentY);
        currentY += (lines.length * 6);
      }
      currentY += 15;
    };

    addSection("VERIFIED QUESTION", `❓ "${data.question}"`);
    addSection("SUMMARY (What You Learned)", getSummaryPoints(data.answer));
    addSection("VERIFIED AI ANSWER", data.answer);

    // Metadata Box
    if (currentY > 230) {
      doc.addPage();
      currentY = 25;
    }

    doc.setDrawColor(230, 230, 230);
    doc.setFillColor(248, 248, 255);
    doc.rect(margin, currentY, contentWidth, 45, 'F');
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 100, 100);
    doc.text("VERIFICATION DETAILS", margin + 5, currentY + 10);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("DETERMINISTIC ID:", margin + 5, currentY + 20);
    doc.setTextColor(107, 70, 193);
    doc.text(verifyId, margin + 5, currentY + 26);
    
    doc.setTextColor(100, 100, 100);
    doc.text("TIMESTAMP:", margin + 5, currentY + 35);
    doc.text(new Date(data.timestamp!).toLocaleString(), margin + 45, currentY + 35);
    doc.text("PROOF TYPE:", margin + 5, currentY + 41);
    doc.text("Demo Verification", margin + 45, currentY + 41);

    // Footer
    const footerY = doc.internal.pageSize.height - 10;
    doc.setFontSize(9);
    doc.setTextColor(180, 180, 180);
    doc.text("Generated by LineraMind — AI Answer Verification Demo", pageWidth / 2, footerY, { align: "center" });

    doc.save(`LineraMind_Verified_Proof_${data.id}.pdf`);
  };

  const formatAnswer = (text: string) => {
    const cleanText = text.replace(/\*\*(.*?)\*\*/g, '$1')
                         .replace(/^\s*[-*]\s+/gm, '')
                         .replace(/###/g, '');

    return cleanText.split('\n\n').map((section, idx) => {
      const trimmed = section.trim();
      if (!trimmed) return null;

      const getIcon = (title: string) => {
        const t = title.toLowerCase();
        if (t.includes('concept')) return '🧠';
        if (t.includes('how it works')) return '⚙️';
        if (t.includes('key components')) return '🧩';
        if (t.includes('characteristics')) return '📌';
        if (t.includes('core function')) return '🎯';
        return '✨';
      };

      if (trimmed.endsWith(':') && trimmed.length < 50) {
        const title = trimmed.replace(':', '');
        return (
          <div key={idx} className="mt-8 mb-4 first:mt-0">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xl">{getIcon(title)}</span>
              <h3 className="text-lg font-bold text-primary uppercase tracking-tight">{title}</h3>
            </div>
          </div>
        );
      }
      return <p key={idx} className="text-foreground/80 leading-relaxed text-base mb-4 last:mb-0">{trimmed}</p>;
    }).filter(Boolean);
  };

  const getSummaryPoints = (text: string) => {
    // Extract key sentences or use simulated points if text is too complex
    // For demo purposes, we'll provide high-quality summary points based on common AI responses
    return [
      "Core operational principles identified and verified.",
      "Deterministic proof generated for state transitions.",
      "Technical architecture validated against specifications.",
      "Verification record committed to simulated microchain."
    ];
  };

  return (
    <div className="min-h-screen bg-background bg-grid-pattern text-foreground flex flex-col">
      <Navbar />
      
      <main className="flex-1 max-w-5xl mx-auto w-full px-4 py-8">
        <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 mb-8 relative">
          <div className="space-y-3">
            <motion.div 
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center border border-primary/20 shadow-lg shadow-primary/5"
            >
              <ShieldCheck className="w-6 h-6 text-primary" />
            </motion.div>
            <div>
              <h1 className="text-3xl font-display font-bold tracking-tight">Verify Record</h1>
              <p className="text-muted-foreground text-base">
                Retrieve and validate your microchain proof.
              </p>
            </div>
          </div>
          
          {data && (
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              className="md:absolute md:top-0 md:right-0"
            >
              <Button 
                onClick={downloadPDF}
                className="px-6 py-5 rounded-xl bg-primary text-primary-foreground font-bold shadow-lg shadow-primary/20 hover:scale-[1.02] transition-all flex items-center gap-2 group"
              >
                <FileDown className="w-5 h-5 group-hover:animate-bounce" />
                Download Verified Answer (PDF)
              </Button>
            </motion.div>
          )}
        </div>

        <form onSubmit={handleVerify} className="max-w-2xl mb-12">
          <div className="flex gap-2 p-1.5 bg-secondary/40 backdrop-blur-md rounded-xl border border-white/10 focus-within:border-primary/50 transition-all shadow-xl">
            <div className="pl-3 flex items-center pointer-events-none text-muted-foreground">
              <Search className="w-4 h-4" />
            </div>
            <input
              type="text"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              placeholder="linera:chain1:42"
              className="flex-1 bg-transparent border-none focus:ring-0 text-foreground placeholder:text-muted-foreground/40 font-mono text-sm h-10"
            />
            <Button
              type="submit"
              disabled={isLoading || !inputValue}
              className="px-6 rounded-lg bg-primary text-primary-foreground font-semibold h-10"
            >
              Verify
            </Button>
          </div>
          
          <AnimatePresence>
            {showSuccess && (
              <motion.div
                initial={{ opacity: 0, y: -5 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="mt-3 flex items-center gap-2 text-green-400 font-medium text-xs"
              >
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>Verified successfully</span>
              </motion.div>
            )}
          </AnimatePresence>
        </form>

        <AnimatePresence mode="wait">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-20">
              <div className="w-10 h-10 border-3 border-primary/20 border-t-primary rounded-full animate-spin mb-4" />
              <p className="text-muted-foreground font-mono text-[10px] uppercase tracking-widest">Querying...</p>
            </div>
          ) : isError ? (
            <motion.div
              key="error"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="bg-destructive/10 border border-destructive/20 rounded-xl p-6 text-center max-w-md mx-auto"
            >
              <AlertCircle className="w-10 h-10 text-destructive mx-auto mb-3" />
              <p className="text-muted-foreground text-sm">Verification failed: ID not found.</p>
            </motion.div>
          ) : data ? (
            <motion.div
              key="data"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-8"
            >
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
                <div className="lg:col-span-1 space-y-6">
                  {/* Summary Section */}
                  <div className="bg-secondary/30 border border-white/5 rounded-2xl p-6 backdrop-blur-sm">
                    <div className="flex items-center gap-2 mb-4">
                      <CheckCircle2 className="w-5 h-5 text-green-400" />
                      <h2 className="text-sm font-bold uppercase tracking-wider">Key Insights</h2>
                    </div>
                    <div className="space-y-3">
                      {getSummaryPoints(data.answer).map((point, i) => (
                        <div key={i} className="flex items-start gap-3">
                          <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-green-400 shrink-0" />
                          <p className="text-xs text-foreground/70 leading-relaxed">{point}</p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Metadata Section */}
                  <div className="bg-black/20 border border-white/5 rounded-2xl p-6">
                    <h3 className="text-[10px] uppercase tracking-widest text-muted-foreground font-bold mb-4">Metadata</h3>
                    <div className="space-y-4">
                      <div className="space-y-1">
                        <div className="text-[9px] text-muted-foreground uppercase">ID</div>
                        <div className="text-[11px] font-mono text-primary break-all">linera:{data.chainId}:{data.id}</div>
                      </div>
                      <div className="space-y-1">
                        <div className="text-[9px] text-muted-foreground uppercase">Type</div>
                        <div className="text-[11px] font-mono text-foreground/60">Demo Proof</div>
                      </div>
                      <div className="space-y-1">
                        <div className="text-[9px] text-muted-foreground uppercase">Date</div>
                        <div className="text-[11px] font-mono text-foreground/60">{new Date(data.timestamp!).toLocaleDateString()}</div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="lg:col-span-2">
                  <TerminalCard title="Verified Record" className="border-primary/20 bg-secondary/20 h-fit max-h-[600px] flex flex-col">
                    <div className="overflow-y-auto pr-2 custom-scrollbar space-y-8 pb-4">
                      <div className="space-y-3">
                        <div className="text-[10px] uppercase tracking-widest text-muted-foreground font-bold">Question</div>
                        <p className="text-foreground text-xl font-semibold leading-tight italic border-l-2 border-primary/40 pl-4 py-1">
                          "{data.question}"
                        </p>
                      </div>

                      <div className="space-y-4">
                        <div className="text-[10px] uppercase tracking-widest text-muted-foreground font-bold">Explanation</div>
                        <div className="bg-white/5 rounded-2xl p-6 border border-white/5">
                          <div className="prose prose-invert max-w-none prose-sm">
                            {formatAnswer(data.answer)}
                          </div>
                        </div>
                      </div>
                    </div>
                  </TerminalCard>
                </div>
              </div>
            </motion.div>
          ) : (
            <div className="py-20 flex flex-col items-center opacity-20">
              <Database className="w-12 h-12 mb-4" />
              <p className="text-xs uppercase tracking-widest font-mono">Standby</p>
            </div>
          )}
        </AnimatePresence>
      </main>
    </div>
  );
}
